FROM python:3.11-slim

WORKDIR /app

COPY . .

# Installer FastAPI et Uvicorn (serveur ASGI)
RUN pip install --no-cache-dir fastapi uvicorn

# Commande de démarrage (Uvicorn pour FastAPI)
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]