version: "3.8"

services:
  phishing-app:
    build: .
    container_name: phishing_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # FastAPI
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI MailHog
